/**
 * (resume, templateId) → the files of a site.
 *
 * The template produces index.html and styles.css; this module adds the
 * README every site ships with and offers the single-document variant the
 * preview iframe needs. It is the only place that knows the set of
 * templates, so adding one is a registry entry and nothing else.
 */
import type { Resume } from "../schema/resume";
import { escapeHtml } from "./escape";
import { creative } from "./creative/meta";
import { developer } from "./developer/meta";
import { minimal } from "./minimal/meta";
import { isTemplateId, type RenderOptions, type Template, type TemplateId, type TemplateMeta } from "./types";

const TEMPLATES: Record<TemplateId, Template> = { minimal, developer, creative };

export const DEFAULT_TEMPLATE: TemplateId = "minimal";

export function templateMetas(): TemplateMeta[] {
  return Object.values(TEMPLATES).map((template) => template.meta);
}

export function templateOf(id: string | null | undefined): Template {
  return TEMPLATES[isTemplateId(id) ? id : DEFAULT_TEMPLATE];
}

export type SiteFiles = Record<"index.html" | "styles.css" | "README.md", string>;

/** Every file the ZIP will contain. */
export function renderSite(
  resume: Resume,
  templateId: string | null | undefined,
  options: RenderOptions = {},
): SiteFiles {
  const template = templateOf(templateId);
  const site = template.render(resume, options);
  return {
    "index.html": site["index.html"],
    "styles.css": site["styles.css"],
    "README.md": readme(resume, template.meta),
  };
}

/**
 * index.html with styles.css inlined, for a blob-URL preview.
 *
 * A blob document cannot resolve a relative stylesheet, so the link tag is
 * replaced by a style element holding the same CSS. The exported file is
 * unchanged; only the preview differs, and only in this one way.
 */
export function inlineForPreview(site: { "index.html": string; "styles.css": string }): string {
  const link = /<link\s+rel="stylesheet"\s+href="\.?\/?styles\.css"\s*\/?>/i;
  // CSS is authored, not user text; the one thing it must not contain is a
  // closing style tag, which would end the element early.
  const css = site["styles.css"].replace(/<\/style/gi, "<\\/style");
  return site["index.html"].replace(link, `<style>\n${css}\n</style>`);
}

/**
 * The README is Markdown, and Markdown is rendered — by GitHub, by every
 * static host's file browser. So the name goes in as plain text: HTML
 * escaped, Markdown syntax characters removed, on one line. The one place
 * user text reaches an output file outside the html tag, and it gets the
 * same discipline.
 */
function markdownSafe(text: string): string {
  return escapeHtml(text)
    .replace(/[\r\n]+/g, " ")
    .replace(/[[\]()!#*_`<>|\\]/g, "")
    .trim();
}

function readme(resume: Resume, meta: TemplateMeta): string {
  const name = markdownSafe(resume.basics.name) || "Portfolio";
  return `# ${name} — portfolio site

Generated by Resume → Portfolio with the "${meta.name}" template. Everything is
static: one HTML file, one stylesheet, no JavaScript, no build step, no
external requests.

## Run it locally

Open \`index.html\` in a browser. That is all.

## Deploy it

Any static host works. Upload the three files, or:

**GitHub Pages** — create a repository, commit these files to its root, then
Settings → Pages → Source: "Deploy from a branch", branch \`main\`, folder \`/\`.
The site will be at \`https://<you>.github.io/<repo>/\`.

**Netlify / Vercel / Cloudflare Pages** — drag the folder onto the dashboard,
or point a new site at a repository holding it. No build command; publish
directory is the root.

## Edit it

\`index.html\` is plain HTML and \`styles.css\` is plain CSS. Colours are
custom properties at the top of the stylesheet. There is nothing to
compile; edit, save, reload.

---

Made with Resume → Portfolio. Your resume never left your browser.
`;
}
